n = int(input('Digite um número: '))
nome = 'Tabuada'
print(f'{nome:=^20}')
print(f'{n} * {1:^2} = {n * 1}')
print(f'{n} * {2:^2} = {n * 2}')
print(f'{n} * {3:^2} = {n * 3}')
print(f'{n} * {4:^2} = {n * 4}')
print(f'{n} * {5:^2} = {n * 5}')
print(f'{n} * {6:^2} = {n * 6}')
print(f'{n} * {7:^2} = {n * 7}')
print(f'{n} * {8:^2} = {n * 8}')
print(f'{n} * {9:^2} = {n * 9}')
print(f'{n} * {10:^2} = {n * 10}')
print('='*20)

